work_dir: ./work_dir/ntu60/xsub/joint1
seed: 1
device: [0]

# --- 数据设置 ---
feeder: feeders.feeder_ntu.Feeder 
train_feeder_args:
  # 核心路径和划分
  data_path: 'data/ntu/NTU60_CS.npz'  
  label_path: 'data/ntu/NTU60_CS.npz'
  split: 'train'
  window_size: 64               
  p_interval: [0.5, 1]                     
  random_shift: false         
  random_move: false           
  random_rot: true              
  bone: false
  vel: false

test_feeder_args:
  # 核心路径和划分
  data_path: 'data/ntu/NTU60_CS.npz'  
  label_path: 'data/ntu/NTU60_CS.npz'
  split: 'test'  
  window_size: 64
  p_interval: [0.95]
  vel: false
  bone: False
  debug: False


# --- 模型设置 ---
model: model.sgt_net.Model
model_args:
  # --- 基础模型配置 ---
  num_nodes: 25
  num_class: 60
  num_person: 2
  dataset_name: ntu_rgb_d  # 数据集名称，用于获取预计算跳数矩阵
  
  # --- 图配置 ---
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

  # --- Dropout配置 ---
  dropout_rate: 0.2
  drop_path_rate: 0.2

# --- SGD优化器设置 ---
optimizer: SGD
base_lr: 0.1
weight_decay: 0.0004
nesterov: True

# --- 学习率调度 ---
lr_scheduler: multistep
step: [35, 55, 75]
lr_decay_rate: 0.1
warm_up_epoch: 5

# --- 训练设置 ---
num_epoch: 90
batch_size: 64
test_batch_size: 128
num_worker: 12

# --- 其他训练参数 ---
loss_type: LSCE
label_smoothing: 0.1

# --- 日志与保存 ---
log_interval: 0
eval_interval: 1
save_interval: 0
save_epoch: 0
print_log: true
save_score: true
show_topk: [1]