work_dir: ./work_dir/nw-ucla/bone_motion
phase: train
seed: 1
device: 0

# --- 数据设置 ---
feeder: feeders.feeder_ucla.Feeder
train_feeder_args:
  data_path: bone_motion
  label_path: train
  debug: false
  random_choose: true
  random_shift: false
  random_move: false
  window_size: 52
  repeat: 5

test_feeder_args:
  data_path: bone_motion
  label_path: val
  debug: false       

# --- 模型设置 (适配 sgt_net.py) ---
model: model.sgt_net.Model
model_args:
  # --- 基础模型配置 ---
  num_nodes: 20
  num_class: 10
  num_person: 1
  dataset_name: nw-ucla
  
  # --- 图配置 ---
  graph: graph.ucla.Graph
  graph_args:
    labeling_mode: spatial
  
  # --- Dropout配置 ---
  dropout_rate: 0.1
  drop_path_rate: 0.15

# --- SGD优化器设置 ---
optimizer: SGD
base_lr: 0.1
weight_decay: 0.0001
nesterov: True

# --- 学习率调度 ---
lr_scheduler: multistep
step: [35, 50]
lr_decay_rate: 0.1
warm_up_epoch: 5

# --- 训练设置 ---
num_epoch: 65
batch_size: 64
test_batch_size: 64
num_worker: 8

# --- 其他训练参数 ---
loss_type: LSCE
label_smoothing: 0.1

# --- 日志与保存 ---
log_interval: 0
eval_interval: 1
save_interval: 0
save_epoch: 0
print_log: true
save_score: true
show_topk: [1]