# --- 主工作目录 ---
work_dir: ./work_dir/ucla_early_fusion_temporal_1layer_multistep # 新目录名，反映配置

# --- 指定要融合训练的模态 ---
modalities: ['joint', 'bone', 'joint_motion', 'bone_motion'] # 保持四模态融合

# --- 测试集标签文件 ---
label_file: 'data/nw-ucla/val_label.pkl' # 确保路径正确


# 数据加载器通用配置 (Feeder)
feeder: feeders.feeder_ucla.Feeder # 使用支持多模态拼接和类别增强的 Feeder
train_feeder_args:
  root_dir: 'data/nw-ucla/all_sqe/all_sqe/'
  split: 'train'
  repeat: 5
  random_choose: true # 启用随机时间采样
  window_size: 64
  apply_rand_view_transform: true # 启用随机视角变换
  center_joint_idx: 1
  num_classes: 10
  max_len: 64
  # --- 添加类别相关增强配置 (基于你的混淆矩阵和之前的讨论) ---
  augment_confused_classes: true                # <<<--- 启用对特定类别的增强
  confused_classes_list: [0, 1, 2, 3, 4, 8, 9]  # <<<--- 指定需要增强的类别 (0-based)
  confused_rotation_range: [-75, 75]            # <<<--- 对这些类别应用稍大的旋转范围
  confused_scale_range: [0.4, 1.6]              # <<<--- 对这些类别应用稍大的缩放范围
  add_gaussian_noise: true                      # <<<--- 对这些类别添加高斯噪声
  gaussian_noise_level: 0.01                    # <<<--- 高斯噪声强度
  # ----------------------------------------------------------
test_feeder_args:
  root_dir: 'data/nw-ucla/all_sqe/all_sqe/'
  split: 'val'
  repeat: 1
  random_choose: false # 验证集不使用随机采样
  window_size: 64
  apply_rand_view_transform: false # 验证集不使用随机变换
  center_joint_idx: 1
  val_pkl_path: 'data/nw-ucla/val_label.pkl'
  num_classes: 10
  max_len: 64
  # --- 测试集不应用类别增强 ---
  augment_confused_classes: false
  add_gaussian_noise: false
  # --------------------------


# 模型配置 (Model)
model: model.SDT_GRUs_Gesture.SDT_GRU_Classifier # 确认使用的是包含 TemporalTransformerBlock 的版本
model_args:
  num_input_dim: 3     # 保持基础维度，main.py会覆盖
  num_nodes: 20
  num_classes: 10
  num_rnn_layers: 2
  num_rnn_units: 128   # 保持 GRU 单元数
  n_heads: 8           # 空间头数
  ffn_dim: 256         # 空间 FFN 维度
  st_layers: 2
  st_dropout_rate: 0.1
  rnn_dropout_rate: 0.1
  classifier_dropout: 0.4 # <<<--- 保持稍微降低的 Dropout (或根据实验调整)
  zoneout_rate: 0.0
  output_attention: False
  use_gap: True # Temporal Attn 内部会处理聚合
  classifier_hidden_dim: 64
  max_seq_len: 64      # 匹配 feeder max_len
  use_conv_proj: true
  conv_kernel_size: 3
  qkv_bias: false
  # --- 启用并配置 Temporal Attention ---
  use_temporal_attn: true      # <<<--- 启用时间注意力
  num_temporal_layers: 1       # <<<--- 设置为 1 层
  temporal_n_heads: 8          # 时间注意力头数 (128 % 8 == 0)
  temporal_ffn_dim: 512      # 时间 FFN 维度 (4 * 128)
  temporal_dropout_rate: 0.1   # 时间注意力块的 Dropout

# -------------------------
# 优化器与学习率
# -------------------------
optimizer: AdamW
base_lr: 0.002             # <<<--- 保持原来的学习率
weight_decay: 0.05         # <<<--- 尝试之前效果较好的较高值 (或根据需要调整)

# --- 学习率调度器 (保持 MultiStep) ---
lr_scheduler: multistep
step: [60, 80]             # <<<--- 保持原来的衰减节点 (可以尝试提前，如 [50, 75])
lr_decay_rate: 0.1
warm_up_epoch: 15          # <<<--- 保持原来的 warmup

# -------------------------
# 训练与测试流程配置
# -------------------------
batch_size: 256          # <<<--- 降低批次大小以防显存不足
test_batch_size: 256     # <<<--- 相应调整
num_epoch: 100           # <<<--- 保持 100 轮
num_worker: 32
loss_type: SmoothCE      # <<<--- 尝试标签平滑

# --- 梯度裁剪 ---
grad_clip: false          # <<<--- 启用梯度裁剪
grad_max: 1.0

# --- 日志与保存 ---
log_interval: 50
eval_interval: 1
save_interval: 0
save_epoch: 0
print_log: true
save_score: true
show_topk: [1]

# --- 早停 ---
early_stop_patience: 30    # <<<--- 保持原来的耐心值 (或适当增加)

# --- 设备和种子 ---
# device: [0]
# seed: 1
base_channel: 3