work_dir: ./work_dir/sdtgru_ucla_run
config: ./config/ucla/nw-ucla.yaml
phase: train
device:
- 0
seed: 1
model: model.SDT_GRUs_Gesture.SDT_GRU_Classifier
model_args:
  num_input_dim: 3
  num_nodes: 20
  num_classes: 10
  num_rnn_layers: 2
  num_rnn_units: 128
  n_heads: 8
  ffn_dim: 256
  st_layers: 2
  st_dropout_rate: 0.1
  rnn_dropout_rate: 0.1
  classifier_dropout: 0.5
  zoneout_rate: 0.0
  output_attention: false
  use_gap: true
  classifier_hidden_dim: 64
weights: null
ignore_weights: []
feeder: feeders.feeder_ucla.Feeder
train_feeder_args:
  root_dir: data/nw-ucla/all_sqe/all_sqe/
  split: train
  data_path: joint
  repeat: 5
  random_choose: true
  window_size: 52
  apply_normalization: false
  apply_rand_view_transform: true
test_feeder_args:
  root_dir: data/nw-ucla/all_sqe/all_sqe/
  split: val
  data_path: joint
  repeat: 1
  random_choose: false
  window_size: 52
  apply_normalization: false
  apply_rand_view_transform: false
num_worker: 4
batch_size: 32
test_batch_size: 64
num_epoch: 80
start_epoch: 0
optimizer: AdamW
base_lr: 0.001
weight_decay: 0.01
step:
- 50
- 70
lr_decay_rate: 0.1
warm_up_epoch: 5
nesterov: false
log_interval: 50
eval_interval: 1
save_interval: 10
save_epoch: 0
print_log: true
save_score: false
show_topk:
- 1
